import { serve } from "https://deno.land/std@0.192.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? ''
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY') ?? ''

    if (!supabaseUrl || !supabaseServiceKey) {
      throw new Error('Server configuration error: Missing Supabase keys.')
    }

    // 1. Create a Supabase client with the caller's JWT to verify their identity and role
    const authHeader = req.headers.get('Authorization')!
    if (!authHeader) {
      return new Response(JSON.stringify({ success: false, message: 'Missing Authorization header' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const userClient = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } }
    })

    const { data: { user }, error: userError } = await userClient.auth.getUser()
    if (userError || !user) {
      return new Response(JSON.stringify({ success: false, message: 'Unauthorized' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    // Check caller's role in profiles
    const { data: callerProfile, error: profileError } = await userClient
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single()

    if (profileError || !callerProfile) {
      return new Response(JSON.stringify({ success: false, message: 'Failed to retrieve caller profile' }), {
        status: 403,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const allowedRoles = ['super_admin', 'admin', 'btc_manager', 'warehouse_manager']
    if (!allowedRoles.includes(callerProfile.role)) {
      return new Response(JSON.stringify({ success: false, message: 'Forbidden: Insufficient permissions to create users' }), {
        status: 403,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    // 2. Extract user data from request body
    const { 
      email, 
      password, 
      full_name, 
      username, 
      role, 
      permissions, 
      status, 
      phone, 
      organization, 
      region_id, 
      area_id, 
      managed_warehouse_ids,
      assigned_warehouse_ids,
      owner_entity_ids,
      access_expires_at
    } = await req.json()

    if (!email || !password || !full_name) {
      return new Response(JSON.stringify({ success: false, message: 'Missing required fields (email, password, full_name)' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    // 3. Create a Supabase client with the Service Role key to perform admin actions
    const adminClient = createClient(supabaseUrl, supabaseServiceKey)

    // 4. Create the user using admin API
    const { data: authData, error: authError } = await adminClient.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
      user_metadata: {
        full_name,
        username,
        role
      }
    })

    if (authError) {
      return new Response(JSON.stringify({ success: false, message: authError.message }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const newUserId = authData.user.id

    // 5. Update the profile that was auto-generated by the handle_new_user trigger
    const profileUpdates = {
      role: role || 'viewer',
      permissions: permissions || ['asset.view'],
      status: status || 'active',
      phone: phone || null,
      organization: organization || null,
      region_id: region_id || null,
      area_id: area_id || null,
      managed_warehouse_ids: managed_warehouse_ids || null,
      assigned_warehouse_ids: assigned_warehouse_ids || null,
      owner_entity_ids: owner_entity_ids || null,
      access_expires_at: access_expires_at || null,
    }

    const { data: updatedProfile, error: updateError } = await adminClient
      .from('profiles')
      .update(profileUpdates)
      .eq('id', newUserId)
      .select()
      .single()

    if (updateError) {
      // We return success but warn about the profile update failure
      return new Response(JSON.stringify({ 
        success: true, 
        message: 'User created in auth, but failed to update profile properties: ' + updateError.message,
        user: authData.user
      }), {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    return new Response(JSON.stringify({ success: true, profile: updatedProfile }), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })

  } catch (err: any) {
    return new Response(JSON.stringify({ success: false, message: err.message || 'Internal Server Error' }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})
