import React, { useState, useEffect } from 'react';
import { X, Loader2, ShieldCheck, AlertTriangle, Building2, FileText, MapPin } from 'lucide-react';
import { Asset, Project, Warehouse } from '../types';
import { useAuth } from '../contexts/AuthContext';
import { fetchAssetIdentifierCandidates } from '../api/assets';
import { COLLATERAL_TYPES, PROPERTY_TYPES, resolveRegionCode, generateNextAssetCode, checkAssetDuplicate } from '../lib/assetIdentifier';
import toast from 'react-hot-toast';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (assetData: Partial<Asset>) => Promise<void>;
  projects: Project[];
  warehouses: Warehouse[];
}

export const CreateAssetModal: React.FC<Props> = ({ isOpen, onClose, onSubmit, projects, warehouses }) => {
  const { profile } = useAuth();
  const [loading, setLoading] = useState(false);
  const [allAssets, setAllAssets] = useState<Asset[]>([]);

  // Asset Code & Collateral Type
  const [collateralType, setCollateralType] = useState('BDS');
  const [customAssetCode, setCustomAssetCode] = useState('');
  const [autoGeneratedCode, setAutoGeneratedCode] = useState('VMT_BDS_00000001');

  // Core Fields
  const [certificateNo, setCertificateNo] = useState('');
  const [projectId, setProjectId] = useState('');
  const [businessProjectName, setBusinessProjectName] = useState('');
  const [subdivision, setSubdivision] = useState('');
  const [lotNo, setLotNo] = useState('');
  const [businessPlotCode, setBusinessPlotCode] = useState('');
  const [area, setArea] = useState('');
  const [ownerName, setOwnerName] = useState('');
  const [warehouseId, setWarehouseId] = useState('');

  // Extended Land & Legal Fields
  const [mapSheetNo, setMapSheetNo] = useState('');
  const [landLotNo, setLandLotNo] = useState('');
  const [province, setProvince] = useState('');
  const [district, setDistrict] = useState('');
  const [ward, setWard] = useState('');
  const [addressDetail, setAddressDetail] = useState('');
  const [usagePurpose, setUsagePurpose] = useState('Đất ở tại đô thị (ODT)');
  const [assetType, setAssetType] = useState('Đất nền');
  const [registryNo, setRegistryNo] = useState('');
  const [registryDate, setRegistryDate] = useState('');
  const [managingUnit, setManagingUnit] = useState('');
  const [certificateGroup, setCertificateGroup] = useState<'so_lon' | 'so_nho'>('so_nho');
  const [usageTermType, setUsageTermType] = useState<'fixed_date' | 'long_term'>('long_term');
  const [usageTermDate, setUsageTermDate] = useState('');
  const [scanFileUrl, setScanFileUrl] = useState('');

  // Mortgage Fields
  const [isMortgaged, setIsMortgaged] = useState(false);
  const [mortgageBank, setMortgageBank] = useState('');
  const [mortgageUnit, setMortgageUnit] = useState('');
  const [mortgageValuation, setMortgageValuation] = useState('');
  const [mortgageReleaseDate, setMortgageReleaseDate] = useState('');
  const [hasSecondBank, setHasSecondBank] = useState(false);
  const [mortgageBank2, setMortgageBank2] = useState('');
  const [mortgageUnit2, setMortgageUnit2] = useState('');
  const [collateralRatio, setCollateralRatio] = useState('');
  const [collateralValue, setCollateralValue] = useState('');
  const [notes, setNotes] = useState('');

  // Duplicate warning
  const [duplicateWarning, setDuplicateWarning] = useState<string | null>(null);

  useEffect(() => {
    if (isOpen) {
      fetchAssetIdentifierCandidates(projectId || undefined)
        .then(candidates => {
          setAllAssets(candidates);
          updateCode(candidates, projectId, collateralType, warehouseId);
        })
        .catch(() => {});
    }
  }, [isOpen, projectId]);

  const updateCode = (assetsList: Asset[], pId: string, cType: string, wId: string) => {
    const wh = warehouses.find(w => w.id === wId);
    const regCode = resolveRegionCode(pId, projects, wh?.region_code);
    const nextCode = generateNextAssetCode(regCode, cType, assetsList);
    setAutoGeneratedCode(nextCode);
  };

  useEffect(() => {
    updateCode(allAssets, projectId, collateralType, warehouseId);
  }, [projectId, collateralType, warehouseId, allAssets]);

  // Live duplicate check
  useEffect(() => {
    if (!isOpen) return;
    const dup = checkAssetDuplicate(
      {
        certificate_no: certificateNo,
        project_id: projectId || null,
        subdivision: subdivision || null,
        lot_no: lotNo || null,
        map_sheet_no: mapSheetNo || null,
        land_lot_no: landLotNo || null,
      },
      allAssets,
      undefined,
      projects.find(p => p.id === projectId)?.name
    );

    if (dup.isDuplicate) {
      setDuplicateWarning(dup.reason || 'Trùng lặp dữ liệu!');
    } else {
      setDuplicateWarning(null);
    }
  }, [certificateNo, projectId, subdivision, lotNo, mapSheetNo, landLotNo, allAssets, isOpen]);

  const handleValuationChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    setMortgageValuation(val);
    if (val && collateralRatio) {
      setCollateralValue(((Number(val) * Number(collateralRatio)) / 100).toString());
    }
  };

  const handleRatioChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    setCollateralRatio(val);
    if (mortgageValuation && val) {
      setCollateralValue(((Number(mortgageValuation) * Number(val)) / 100).toString());
    }
  };

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!certificateNo.trim() || !profile) return;

    if (duplicateWarning) {
      toast.error(duplicateWarning);
      return;
    }

    setLoading(true);
    try {
      const finalAssetCode = customAssetCode.trim() || autoGeneratedCode;

      await onSubmit({
        asset_code: finalAssetCode,
        collateral_type: collateralType,
        certificate_no: certificateNo.trim(),
        project_id: projectId || null,
        business_project_name: businessProjectName.trim() || null,
        subdivision: subdivision.trim() || null,
        lot_no: lotNo.trim() || null,
        business_plot_code: businessPlotCode.trim() || null,
        area: area ? Number(area) : null,
        owner_name: ownerName.trim() || null,
        warehouse_id: warehouseId || null,

        map_sheet_no: mapSheetNo.trim() || null,
        land_lot_no: landLotNo.trim() || null,
        province: province.trim() || null,
        district: district.trim() || null,
        ward: ward.trim() || null,
        address_detail: addressDetail.trim() || null,
        usage_purpose: usagePurpose || null,
        asset_type: assetType || null,
        registry_no: registryNo.trim() || null,
        registry_date: registryDate || null,
        managing_unit: managingUnit.trim() || null,
        certificate_group: certificateGroup,
        usage_term_type: usageTermType,
        usage_term_date: usageTermType === 'fixed_date' ? (usageTermDate || null) : null,
        scan_file_url: scanFileUrl.trim() || null,

        custody_status: 'in_stock',
        lifecycle_status: 'active',
        sale_status: 'not_ready',
        mortgage_status: isMortgaged ? 'mortgaged' : 'none',
        mortgage_bank: isMortgaged ? mortgageBank.trim() : null,
        mortgage_unit: isMortgaged ? mortgageUnit.trim() : null,
        mortgage_bank_2: isMortgaged && hasSecondBank ? mortgageBank2.trim() : null,
        mortgage_unit_2: isMortgaged && hasSecondBank ? mortgageUnit2.trim() : null,
        mortgage_valuation: isMortgaged && mortgageValuation ? Number(mortgageValuation) : null,
        collateral_ratio: isMortgaged && collateralRatio ? Number(collateralRatio) : null,
        collateral_value: isMortgaged && collateralValue ? Number(collateralValue) : null,
        mortgage_expected_release_date: isMortgaged ? (mortgageReleaseDate || null) : null,
        notes: notes.trim() || null,
      });

      toast.success('Khai báo GCN thành công!');
      onClose();
      // Reset form
      setCertificateNo('');
      setProjectId('');
      setBusinessProjectName('');
      setSubdivision('');
      setLotNo('');
      setBusinessPlotCode('');
      setArea('');
      setOwnerName('');
      setWarehouseId('');
      setCustomAssetCode('');
      setMapSheetNo('');
      setLandLotNo('');
      setProvince('');
      setDistrict('');
      setWard('');
      setAddressDetail('');
      setScanFileUrl('');
      setIsMortgaged(false);
      setMortgageBank('');
      setMortgageUnit('');
      setMortgageValuation('');
      setMortgageReleaseDate('');
      setHasSecondBank(false);
      setMortgageBank2('');
      setMortgageUnit2('');
      setCollateralRatio('');
      setCollateralValue('');
      setNotes('');
    } catch (error: any) {
      toast.error('Lỗi: ' + error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="bg-white rounded-xl shadow-2xl max-w-4xl w-full max-h-[92vh] flex flex-col overflow-hidden border border-gray-200">
        <div className="flex items-center justify-between px-6 py-4 bg-[#1E3A8A] text-white">
          <div className="flex items-center space-x-3">
            <div className="p-2 bg-white/10 rounded-lg">
              <Building2 className="w-5 h-5 text-blue-200" />
            </div>
            <div>
              <h3 className="text-base font-bold">Khai Báo GCN QSDĐ / Tài Sản Mới</h3>
              <p className="text-xs text-blue-200">
                Tự động định danh mã tài sản theo Vùng và Loại tài sản đảm bảo (TSĐB)
              </p>
            </div>
          </div>
          <button onClick={onClose} className="text-white/80 hover:text-white p-1 rounded-lg hover:bg-white/10">
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-6 overflow-y-auto flex-1">
          {duplicateWarning && (
            <div className="p-3 bg-red-50 border border-red-200 rounded-lg flex items-start space-x-2 text-red-800 text-xs animate-pulse">
              <AlertTriangle className="w-4 h-4 text-red-600 flex-shrink-0 mt-0.5" />
              <div>
                <span className="font-bold">Cảnh báo trùng lặp: </span>
                {duplicateWarning}
              </div>
            </div>
          )}

          {/* SECTION 1: ĐỊNH DANH MÃ TÀI SẢN & TSĐB */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-gray-900 uppercase tracking-wider flex items-center border-b pb-2">
              <ShieldCheck className="w-4 h-4 text-[#1E3A8A] mr-1.5" />
              1. Định Danh Mã Tài Sản & Loại TSĐB
            </h4>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  Mã Định Danh (Hệ Thống Tự Sinh)
                </label>
                <div className="flex items-center space-x-1.5">
                  <input
                    type="text"
                    value={customAssetCode || autoGeneratedCode}
                    onChange={e => setCustomAssetCode(e.target.value)}
                    placeholder="VMT_BDS_00001"
                    className="w-full px-3 py-2 border rounded-md text-xs font-mono font-bold text-[#1E3A8A] bg-blue-50/50 border-blue-200 focus:bg-white"
                  />
                </div>
                <span className="text-[10px] text-gray-500 mt-0.5 block">
                  Quy tắc: [Vùng]_[Loại TSĐB]_[Số thứ tự]
                </span>
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  Loại Tài Sản Đảm Bảo (TSĐB) <span className="text-red-500">*</span>
                </label>
                <select
                  value={collateralType}
                  onChange={e => setCollateralType(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300 focus:ring-1 focus:ring-blue-500"
                >
                  {COLLATERAL_TYPES.map(ct => (
                    <option key={ct.code} value={ct.code}>
                      [{ct.shortName}] {ct.name}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  Nhóm Sổ Quản Lý
                </label>
                <select
                  value={certificateGroup}
                  onChange={e => setCertificateGroup(e.target.value as any)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                >
                  <option value="so_nho">Sổ nhỏ (Lô / Căn hộ / Liền kề)</option>
                  <option value="so_lon">Sổ lớn (Tổng DA / Khu đất mẹ)</option>
                </select>
              </div>
            </div>
          </div>

          {/* SECTION 2: PHÁP LÝ GCN */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-gray-900 uppercase tracking-wider flex items-center border-b pb-2">
              <FileText className="w-4 h-4 text-[#1E3A8A] mr-1.5" />
              2. Pháp Lý & Thông Tin Giấy Chứng Nhận
            </h4>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  Số GCN QSDĐ <span className="text-red-500">*</span>
                </label>
                <input
                  required
                  type="text"
                  value={certificateNo}
                  onChange={e => setCertificateNo(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs font-bold text-[#1E3A8A] border-gray-300 focus:ring-1 focus:ring-blue-500"
                  placeholder="VD: CQ 123456"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  Số Vào Sổ Cấp GCN
                </label>
                <input
                  type="text"
                  value={registryNo}
                  onChange={e => setRegistryNo(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="VD: CH 01234"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  Ngày Vào Sổ Cấp GCN
                </label>
                <input
                  type="date"
                  value={registryDate}
                  onChange={e => setRegistryDate(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                />
              </div>

              <div className="md:col-span-2">
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  Chủ Sở Hữu Đứng Tên Trên GCN
                </label>
                <input
                  type="text"
                  value={ownerName}
                  onChange={e => setOwnerName(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="Công ty Cổ phần Đầu tư VMT..."
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  Đơn Vị Quản Lý Sổ
                </label>
                <input
                  type="text"
                  value={managingUnit}
                  onChange={e => setManagingUnit(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="Ban Nguồn Vốn / Sở TNMT..."
                />
              </div>
            </div>
          </div>

          {/* SECTION 3: VỊ TRÍ, PHÂN KHU & THỬA ĐẤT */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-gray-900 uppercase tracking-wider flex items-center border-b pb-2">
              <MapPin className="w-4 h-4 text-[#1E3A8A] mr-1.5" />
              3. Vị Trí, Phân Khu & Thửa Đất
            </h4>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Dự Án (Pháp lý)</label>
                <select
                  value={projectId}
                  onChange={e => setProjectId(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300 focus:ring-1 focus:ring-blue-500"
                >
                  <option value="">-- Chọn dự án pháp lý --</option>
                  {projects.map(p => (
                    <option key={p.id} value={p.id}>
                      {p.name} {p.areas?.name ? `(${p.areas.name})` : ''}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-medium text-blue-900 mb-1 flex items-center justify-between">
                  <span>Tên Dự Án Kinh Doanh</span>
                  <span className="text-[10px] text-blue-600 font-normal">Tên bán hàng</span>
                </label>
                <input
                  type="text"
                  value={businessProjectName}
                  onChange={e => setBusinessProjectName(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-blue-200 bg-blue-50/20 focus:ring-1 focus:ring-blue-500"
                  placeholder="VD: Cồn Dầu, Spana, Cora..."
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  Phân Khu <span className="text-blue-600 font-bold">(Cột riêng)</span>
                </label>
                <input
                  type="text"
                  value={subdivision}
                  onChange={e => setSubdivision(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="VD: Phân khu A, Block B..."
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  Số Lô / Thửa (Mã Lô Pháp Lý)
                </label>
                <input
                  type="text"
                  value={lotNo}
                  onChange={e => setLotNo(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="VD: Lô A-12, LK-04..."
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-blue-900 mb-1 flex items-center justify-between">
                  <span>Mã Lô Kinh Doanh</span>
                  <span className="text-[10px] text-blue-600 font-normal">Mã bán hàng</span>
                </label>
                <input
                  type="text"
                  value={businessPlotCode}
                  onChange={e => setBusinessPlotCode(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-blue-200 bg-blue-50/20 focus:ring-1 focus:ring-blue-500"
                  placeholder="VD: LK02-15, BT-VIP-08..."
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Số Thửa Đất</label>
                <input
                  type="text"
                  value={landLotNo}
                  onChange={e => setLandLotNo(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="VD: 112"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Số Tờ Bản Đồ</label>
                <input
                  type="text"
                  value={mapSheetNo}
                  onChange={e => setMapSheetNo(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="VD: 04"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Diện Tích (m²)</label>
                <input
                  type="number"
                  step="0.01"
                  min="0"
                  value={area}
                  onChange={e => setArea(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs font-semibold border-gray-300"
                  placeholder="VD: 450.5"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Tỉnh / Thành Phố</label>
                <input
                  type="text"
                  value={province}
                  onChange={e => setProvince(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="TP. Hồ Chí Minh..."
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Quận / Huyện</label>
                <input
                  type="text"
                  value={district}
                  onChange={e => setDistrict(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="Quận 2..."
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Phường / Xã</label>
                <input
                  type="text"
                  value={ward}
                  onChange={e => setWard(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="Phường An Phú..."
                />
              </div>

              <div className="md:col-span-3">
                <label className="block text-xs font-medium text-gray-700 mb-1">Địa Chỉ Chi Tiết</label>
                <input
                  type="text"
                  value={addressDetail}
                  onChange={e => setAddressDetail(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="Số nhà, đường phố..."
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Loại Tài Sản</label>
                <select
                  value={assetType}
                  onChange={e => setAssetType(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300 focus:ring-1 focus:ring-blue-500"
                >
                  {PROPERTY_TYPES.map(pt => (
                    <option key={pt} value={pt}>
                      {pt}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Mục Đích Sử Dụng</label>
                <input
                  type="text"
                  value={usagePurpose}
                  onChange={e => setUsagePurpose(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="Đất ở tại đô thị (ODT)..."
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Thời Hạn Sử Dụng</label>
                <div className="flex space-x-2">
                  <select
                    value={usageTermType}
                    onChange={e => setUsageTermType(e.target.value as any)}
                    className="w-1/2 px-2 py-2 border rounded-md text-xs border-gray-300"
                  >
                    <option value="long_term">Lâu dài</option>
                    <option value="fixed_date">Có thời hạn</option>
                  </select>
                  {usageTermType === 'fixed_date' && (
                    <input
                      type="date"
                      value={usageTermDate}
                      onChange={e => setUsageTermDate(e.target.value)}
                      className="w-1/2 px-2 py-2 border rounded-md text-xs border-gray-300"
                    />
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* SECTION 4: KHO & THẾ CHẤP */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-gray-900 uppercase tracking-wider flex items-center border-b pb-2">
              <Building2 className="w-4 h-4 text-[#1E3A8A] mr-1.5" />
              4. Kho Quản Lý & Hồ Sơ Thế Chấp
            </h4>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Kho Quản Lý</label>
                <select
                  value={warehouseId}
                  onChange={e => setWarehouseId(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                >
                  <option value="">-- Chọn kho giữ sổ --</option>
                  {warehouses.map(w => (
                    <option key={w.id} value={w.id}>
                      {w.name} {w.is_central ? '(Trung tâm)' : ''}
                    </option>
                  ))}
                </select>
              </div>

              <div className="md:col-span-2 flex items-center pt-5">
                <label className="flex items-center space-x-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={isMortgaged}
                    onChange={e => setIsMortgaged(e.target.checked)}
                    className="w-4 h-4 text-blue-600 rounded border-gray-300"
                  />
                  <span className="text-xs font-semibold text-gray-800">
                    Tài sản đang được thế chấp tại Ngân hàng
                  </span>
                </label>
              </div>
            </div>

            {isMortgaged && (
              <div className="p-4 bg-amber-50/60 border border-amber-200 rounded-lg space-y-3">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-medium text-gray-700 mb-1">
                      Ngân Hàng Nhận Thế Chấp (NH 1)
                    </label>
                    <input
                      type="text"
                      value={mortgageBank}
                      onChange={e => setMortgageBank(e.target.value)}
                      placeholder="BIDV, VCB..."
                      className="w-full px-3 py-2 border rounded-md text-xs bg-white border-gray-300"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-medium text-gray-700 mb-1">
                      Đơn Vị Thực Hiện Thế Chấp (Đơn vị 1)
                    </label>
                    <input
                      type="text"
                      value={mortgageUnit}
                      onChange={e => setMortgageUnit(e.target.value)}
                      placeholder="Ban Nguồn Vốn..."
                      className="w-full px-3 py-2 border rounded-md text-xs bg-white border-gray-300"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-medium text-gray-700 mb-1">
                      Giá Trị Định Giá (VNĐ)
                    </label>
                    <input
                      type="number"
                      value={mortgageValuation}
                      onChange={handleValuationChange}
                      placeholder="35000000000"
                      className="w-full px-3 py-2 border rounded-md text-xs bg-white border-gray-300"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-medium text-gray-700 mb-1">
                      Tỷ Lệ Đảm Bảo (%) & Giá Trị Đảm Bảo (VNĐ)
                    </label>
                    <div className="flex space-x-2">
                      <input
                        type="number"
                        value={collateralRatio}
                        onChange={handleRatioChange}
                        placeholder="%"
                        className="w-20 px-2 py-2 border rounded-md text-xs bg-white border-gray-300"
                      />
                      <input
                        type="number"
                        value={collateralValue}
                        onChange={e => setCollateralValue(e.target.value)}
                        placeholder="Giá trị đảm bảo (VNĐ)"
                        className="flex-1 px-3 py-2 border rounded-md text-xs bg-white border-gray-300"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-xs font-medium text-gray-700 mb-1">
                      Ngày Dự Kiến Giải Chấp
                    </label>
                    <input
                      type="date"
                      value={mortgageReleaseDate}
                      onChange={e => setMortgageReleaseDate(e.target.value)}
                      className="w-full px-3 py-2 border rounded-md text-xs bg-white border-gray-300"
                    />
                  </div>

                  <div className="flex items-center pt-5">
                    <label className="flex items-center space-x-2 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={hasSecondBank}
                        onChange={e => setHasSecondBank(e.target.checked)}
                        className="w-4 h-4 text-blue-600 rounded border-gray-300"
                      />
                      <span className="text-xs text-gray-700">Có đồng thế chấp / NH 2</span>
                    </label>
                  </div>
                </div>

                {hasSecondBank && (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2 border-t border-amber-200">
                    <div>
                      <label className="block text-xs font-medium text-gray-700 mb-1">
                        Ngân hàng nhận thế chấp 2
                      </label>
                      <input
                        type="text"
                        value={mortgageBank2}
                        onChange={e => setMortgageBank2(e.target.value)}
                        placeholder="Tên NH 2..."
                        className="w-full px-3 py-2 border rounded-md text-xs bg-white border-gray-300"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-gray-700 mb-1">
                        Đơn vị vay 2
                      </label>
                      <input
                        type="text"
                        value={mortgageUnit2}
                        onChange={e => setMortgageUnit2(e.target.value)}
                        placeholder="Đơn vị 2..."
                        className="w-full px-3 py-2 border rounded-md text-xs bg-white border-gray-300"
                      />
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* SECTION 5: FILE SCAN & GHI CHÚ */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-gray-900 uppercase tracking-wider flex items-center border-b pb-2">
              <FileText className="w-4 h-4 text-[#1E3A8A] mr-1.5" />
              5. File Scan & Ghi Chú
            </h4>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">
                  Đường dẫn / File scan GCN (URL)
                </label>
                <input
                  type="text"
                  value={scanFileUrl}
                  onChange={e => setScanFileUrl(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="https://storage.example.com/scan-gcn.pdf"
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Ghi Chú</label>
                <input
                  type="text"
                  value={notes}
                  onChange={e => setNotes(e.target.value)}
                  className="w-full px-3 py-2 border rounded-md text-xs border-gray-300"
                  placeholder="Ghi chú thêm về GCN..."
                />
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 border border-gray-300 rounded-lg text-xs font-medium text-gray-700 hover:bg-gray-50"
            >
              Hủy
            </button>
            <button
              type="submit"
              disabled={loading || !!duplicateWarning}
              className="px-5 py-2 bg-[#1E3A8A] text-white rounded-lg text-xs font-bold hover:bg-blue-800 disabled:opacity-50 disabled:cursor-not-allowed flex items-center shadow-sm"
            >
              {loading && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
              Khai Báo GCN
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
